### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Aezix** [Garulf/Playnite-Plugin#16]
Please type any relevant information here

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\crodm\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.6.0\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
  File "C:\Users\crodm\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.6.0\lib\flox\__init__.py", line 139, in _query
    self.query(query)
  File "C:\Users\crodm\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.6.0\plugin\main.py", line 98, in query
    self.games = pn.import_games(self.playnite_path)
  File "C:\Users\crodm\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.6.0\plugin\playnite.py", line 13, in import_games
    library_file = Path(data_folder, 'ExtensionsData', SCRIPT_NAME, file_name)
  File "pathlib.py", line 1041, in __new__
  File "pathlib.py", line 682, in _from_parts
  File "pathlib.py", line 666, in _parse_args
TypeError: expected str, bytes or os.PathLike object, not NoneType

```
</p>
</details>

**Comment by Garulf** [comment]
Please see: https://github.com/Garulf/Playnite-Plugin/issues/12#issuecomment-1221375996
