### ISSUE TITLE
TypeError consistently showing up

### ISSUE THREAD

**Issue by xcloudx01** [Garulf/Playnite-Plugin#20]
Please type any relevant information here
Recently installed the app, each search result shows a type error in the search results?

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\cloud\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.6.0\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
  File "C:\Users\cloud\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.6.0\lib\flox\__init__.py", line 139, in _query
    self.query(query)
  File "C:\Users\cloud\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.6.0\plugin\main.py", line 98, in query
    self.games = pn.import_games(self.playnite_path)
  File "C:\Users\cloud\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.6.0\plugin\playnite.py", line 13, in import_games
    library_file = Path(data_folder, 'ExtensionsData', SCRIPT_NAME, file_name)
  File "C:\Users\cloud\anaconda3\lib\pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Users\cloud\anaconda3\lib\pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\cloud\anaconda3\lib\pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```
</p>
</details>

**Comment by xcloudx01** [comment]
Ok I figured it out.

The Playnite plugin says "Playnite User Directory:" that I had to input, I was putting in where Playnite is installed, but I googled it and I had to instead use:

C:\Users\USERNAME_HERE\AppData\Roaming\Playnite\

Though I also had an issue with the Playnite User Directory not being saved when I closed the settings and it'd revert to blank. Maybe that was causing the type error? Either way I just tried a few times and then it stuck and now the type error is fixed. (Playnite recognized the injection and asked for a plugin install, clicked yes, now it works 😃)
