### ISSUE TITLE
Playnite Plugin fails to load

### ISSUE THREAD

**Issue by Daniel-Lethem** [Garulf/Playnite-Plugin#26]
[2023-02-07.txt](https://github.com/Garulf/Playnite-Plugin/files/10673740/2023-02-07.txt)

Exception message:

Flow Launcher version: 1.12.1
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\lethe\AppData\Local\Programs\Python\Python310\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 02/07/2023 11:54:28
Exception:
Playnite Exception: 
Websites: https://github.com/Garulf/playnite-plugin
Author: Garulf
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\lethe\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\run.py", line 9, in <module>
    from plugin.main import Playnite
  File "C:\Users\lethe\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox
  File "C:\Users\lethe\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\lib\flox\__init__.py", line 50, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\lethe\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\run.py", line 9, in <module>
    from plugin.main import Playnite
  File "C:\Users\lethe\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox
  File "C:\Users\lethe\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\lib\flox\__init__.py", line 50, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 821
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 785
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Strange. Not aware of any reason the plugin is having trouble detecting your Flow Launcher installation. I'm looking into this.

**Comment by AFaustini** [comment]
Almost same Error here

Flow Launcher version: 1.15.0
OS Version: 22621.1702
IntPtr Length: 8
x64: True

Python Path: D:\Programas\FlowLauncher\app-1.15.0\UserData\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: D:\Programas\FlowLauncher\app-1.15.0\UserData\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 05/23/2023 15:46:52
Exception:
[2023-05-23.txt](https://github.com/Garulf/Playnite-Plugin/files/11547409/2023-05-23.txt)

Playnite Exception: 
Websites: https://github.com/Garulf/playnite-plugin
Author: Garulf
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "D:\Programas\FlowLauncher\app-1.15.0\UserData\Plugins\Playnite-2.0.0\run.py", line 9, in <module>
    from plugin.main import Playnite
  File "D:\Programas\FlowLauncher\app-1.15.0\UserData\Plugins\Playnite-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox
  File "D:\Programas\FlowLauncher\app-1.15.0\UserData\Plugins\Playnite-2.0.0\lib\flox\__init__.py", line 46, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "D:\Programas\FlowLauncher\app-1.15.0\UserData\Plugins\Playnite-2.0.0\run.py", line 9, in <module>
    from plugin.main import Playnite
  File "D:\Programas\FlowLauncher\app-1.15.0\UserData\Plugins\Playnite-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox
  File "D:\Programas\FlowLauncher\app-1.15.0\UserData\Plugins\Playnite-2.0.0\lib\flox\__init__.py", line 46, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 826
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 800
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by AFaustini** [comment]
When i manually remove all plugin folders and reinstall the plugin, works again

**Comment by AFaustini** [comment]
When i manually remove all plugin folders and reinstall the plugin, works again

**Comment by Garulf** [comment]
This was flox guessing at the Flow Launcher directory and giving up.

v3.0.0 drops flox entirely and runs on Flow's python_v2 runtime, where Flow hands the plugin its paths directly, so there is no detection left to fail. Note that it needs a current Flow Launcher for that runtime.

Closing as fixed by the rewrite: https://github.com/Garulf/Playnite-Plugin/releases/tag/v3.0.0
