### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by asifthatwouldeverhappen** [Garulf/Playnite-Plugin#29]
Please type any relevant information here

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\RRG\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RRG\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\lib\flox\__init__.py", line 131, in _query
    self.query(query)
  File "C:\Users\RRG\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\plugin\main.py", line 28, in query
    games = self.pn.search(query, self.applied_filters)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RRG\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\plugin\playnite.py", line 55, in search
    games = self.get_games()
            ^^^^^^^^^^^^^^^^
  File "C:\Users\RRG\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\plugin\playnite.py", line 48, in get_games
    data = json.load(f)
           ^^^^^^^^^^^^
  File "C:\Users\RRG\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\RRG\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RRG\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RRG\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
</p>
</details>

**Comment by Garulf** [comment]
The plugin is having trouble reading the database from Playnite. Do you have the Playnite plugin installed? 

![image](https://user-images.githubusercontent.com/535299/222207089-6bfe830b-4079-4592-adcc-2e6a5f1fc319.png)


If so you may need to have the plugin update the index by going here:

![image](https://user-images.githubusercontent.com/535299/222207503-e135e890-0c07-406e-8367-4216d948007a.png)
