### ISSUE TITLE
"Flow Launcher got an error"

### ISSUE THREAD

**Issue by xcloudx01** [Garulf/Playnite-Plugin#32]
Searching "PN" in Flow Launcher results in the following error:

```
Flow Launcher version: 1.15.0
OS Version: 22621.1778
IntPtr Length: 8
x64: True

Python Path: C:\Users\cloud\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 06/09/2023 15:28:06
Exception:
Playnite Exception: 
Websites: https://github.com/Garulf/playnite-plugin
Author: Garulf
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\cloud\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\run.py", line 9, in <module>
    from plugin.main import Playnite
  File "C:\Users\cloud\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox
  File "C:\Users\cloud\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\lib\flox\__init__.py", line 46, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\cloud\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\run.py", line 9, in <module>
    from plugin.main import Playnite
  File "C:\Users\cloud\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox
  File "C:\Users\cloud\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\lib\flox\__init__.py", line 46, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 836
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 837
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Re-launching Flow Launcher shows the following error:
```
Failed to Init Plugins
Plugins: Playnite - fail to load and would be disabled, pleasse contact plugin creator for help
```

I have attempted to re-install the plugin without success. Flow Launcher is installed here: `C:\Users\cloud\AppData\Local\FlowLauncher\Flow.Launcher.exe`

Log: [2023-06-09.txt](https://github.com/Garulf/Playnite-Plugin/files/11702569/2023-06-09.txt)

**Comment by Garulf** [comment]
This was flox guessing at the Flow Launcher directory and giving up.

v3.0.0 drops flox entirely and runs on Flow's python_v2 runtime, where Flow hands the plugin its paths directly, so there is no detection left to fail. Note that it needs a current Flow Launcher for that runtime.

Closing as fixed by the rewrite: https://github.com/Garulf/Playnite-Plugin/releases/tag/v3.0.0
