### ISSUE TITLE
Got an error please help

### ISSUE THREAD

**Issue by Datatrax** [Garulf/Playnite-Plugin#35]
Flow Launcher version: 1.16.2
OS Version: 22621.2861
IntPtr Length: 8
x64: True

Python Path: C:\Users\Prozac\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 12/20/2023 11:22:14
Exception:
Playnite Exception: 
Websites: https://github.com/Garulf/playnite-plugin
Author: Garulf
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\Prozac\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\run.py", line 9, in <module>
    from plugin.main import Playnite
  File "C:\Users\Prozac\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox
  File "C:\Users\Prozac\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\lib\flox\__init__.py", line 50, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\Prozac\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\run.py", line 9, in <module>
    from plugin.main import Playnite
  File "C:\Users\Prozac\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox
  File "C:\Users\Prozac\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\lib\flox\__init__.py", line 50, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Sorry looks like the plugin heuristics are failing to detect your Flow Launcher installation. 

I am slowly fixing this issue across all my plugins.

**Comment by xcloudx01** [comment]
Did you get any update on this? As I am having the same issue

**Comment by Garulf** [comment]
This was flox guessing at the Flow Launcher directory and giving up.

v3.0.0 drops flox entirely and runs on Flow's python_v2 runtime, where Flow hands the plugin its paths directly, so there is no detection left to fail. Note that it needs a current Flow Launcher for that runtime.

Closing as fixed by the rewrite: https://github.com/Garulf/Playnite-Plugin/releases/tag/v3.0.0
