### ISSUE TITLE
Crash on searching for Playnite game with plugin

### ISSUE THREAD

**Issue by Obspogon** [Garulf/Playnite-Plugin#36]
```
Flow Launcher version: 1.16.2
OS Version: 19045.3803
IntPtr Length: 8
x64: True

Python Path: C:\Users\alico\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 12/26/2023 20:19:53
Exception:
Playnite Exception: 
Websites: https://github.com/Garulf/playnite-plugin
Author: Garulf
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\alico\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\run.py", line 9, in <module>
    from plugin.main import Playnite
  File "C:\Users\alico\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox
  File "C:\Users\alico\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\lib\flox\__init__.py", line 50, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\alico\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\run.py", line 9, in <module>
    from plugin.main import Playnite
  File "C:\Users\alico\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox
  File "C:\Users\alico\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\lib\flox\__init__.py", line 50, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

[2023-12-26.txt](https://github.com/Garulf/Playnite-Plugin/files/13774472/2023-12-26.txt)

**Comment by DelmorS** [comment]
The same problem happened for me, "Unable to locate Launcher directory". But, when I updated Flow Launcher to version 1.17, everything started working properly.

**Comment by Obspogon** [comment]
same here
