### ISSUE TITLE
Unable to locate Launcher directory

### ISSUE THREAD

**Issue by Terael76** [Garulf/Playnite-Plugin#37]
The plugin worked perfectly, but recently I got an error.
Even a new installation did not help

can u help? 

Flow Launcher version: 1.16.2
OS Version: 22631.3527
IntPtr Length: 8
x64: True

Python Path: C:\Users\info\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 05/14/2024 16:09:58
Exception:
Playnite Exception: 
Websites: https://github.com/Garulf/playnite-plugin
Author: Garulf
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\info\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\run.py", line 9, in <module>
    from plugin.main import Playnite
  File "C:\Users\info\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox
  File "C:\Users\info\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\lib\flox\__init__.py", line 50, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\info\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\run.py", line 9, in <module>
    from plugin.main import Playnite
  File "C:\Users\info\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox
  File "C:\Users\info\AppData\Roaming\FlowLauncher\Plugins\Playnite-2.0.0\lib\flox\__init__.py", line 50, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2024-05-14.txt](https://github.com/Garulf/Playnite-Plugin/files/15309637/2024-05-14.txt)

**Comment by Terael76** [comment]
After that i got this message and then the plugin is deactivated:
![image](https://github.com/Garulf/Playnite-Plugin/assets/68641824/574e0a1e-1271-438c-b276-90f7823439fc)

**Comment by Terael76** [comment]
Forget my issue... after Updating PLaynight everything works well. my fault! :D
