### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by ghost** [Garulf/Playnite-Plugin#8]
Flow Launcher version: 1.9.2
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 02/28/2022 18:59:28
Exception:
System.IO.InvalidDataException: Playnite|Traceback (most recent call last):
  File "C:\Users\Ataberk\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.5.1\run.py", line 12, in <module>
    Playnite()
  File "C:\Users\Ataberk\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.5.1\lib\flox\__init__.py", line 107, in __init__
    super().__init__(self.api)
  File "C:\Users\Ataberk\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.5.1\lib\flox\launcher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\Ataberk\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.5.1\lib\flox\__init__.py", line 113, in _query
    self.query(query)
  File "C:\Users\Ataberk\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.5.1\plugin\main.py", line 98, in query
    self.load_settings()
  File "C:\Users\Ataberk\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.5.1\plugin\main.py", line 25, in load_settings
    self.playnite_path = self.settings.setdefault('playnite_path', str(pn.DATA_FOLDER))
  File "C:\Users\Ataberk\AppData\Roaming\FlowLauncher\Plugins\Playnite-1.5.1\lib\flox\__init__.py", line 335, in settings
    os.mkdir(os.path.dirname(self.settings_path))
FileNotFoundError: [WinError 3] Sistem belirtilen yolu bulamıyor: 'C:\\Users\\Ataberk\\AppData\\Local\\Settings\\Plugins\\Process Killer'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
I'm very confused by this line here: 
```
FileNotFoundError: [WinError 3] Sistem belirtilen yolu bulamıyor: 'C:\Users\Ataberk\AppData\Local\Settings\Plugins\Process Killer'
```

The plugin is looking for settings for a completely unrelated plugin in the wrong folder... 

Could you please open `powershell.exe` and type the following: `Get-Item Env:LOCALAPPDATA` & `Get-Item Env:APPDATA` and post the output here?

**Comment by ghost** [comment]
PS C:\Users\Ataberk> Get-Item Env:LOCALAPPDATA

Name                           Value
----                           -----
LOCALAPPDATA                   C:\Users\Ataberk\AppData\Local


PS C:\Users\Ataberk> Get-Item Env:APPDATA

Name                           Value
----                           -----
APPDATA                        C:\Users\Ataberk\AppData\Roaming

**Comment by Garulf** [comment]
> PS C:\Users\Ataberk> Get-Item Env:LOCALAPPDATA
> 
> 
> 
> Name                           Value
> 
> ----                           -----
> 
> LOCALAPPDATA                   C:\Users\Ataberk\AppData\Local
> 
> 
> 
> 
> 
> PS C:\Users\Ataberk> Get-Item Env:APPDATA
> 
> 
> 
> Name                           Value
> 
> ----                           -----
> 
> APPDATA                        C:\Users\Ataberk\AppData\Roaming
> 
> 
> 
> 

Everything looks normal. I'm still trying to narrow down what exactly is causing this issue for you. Could you please provide the `.log` file in the Flow Launcher Playnite plugins main folder? Also I'd like to see what your `plugin.json` file says. That file is how the determine the plugin name and your initial log shows it's pulling a completely different name.

**Comment by Garulf** [comment]
Should be much fixed in https://github.com/Garulf/Playnite-Plugin/pull/23

version 2.0.0
